### ISSUE TITLE
Prueba Git

### ISSUE THREAD

**Issue by PruebasTere** [Tere-Cepero/Prueba1Nov#1]

**Comment by PruebasTere** [comment]
Como empezamos?

**Comment by Angelmon18** [comment]
Podríamos dividir el texto, mitad y mitad, y posteriormente revisar

**Comment by PruebasTere** [comment]
Pues tu dime que mitas quieres :)

**Comment by Angelmon18** [comment]
Si quieres, tú la primera mitad y yo la segunda, comienzo en la parte que dice "Para las generación eficiente de awareness..."

**Comment by PruebasTere** [comment]
@Angel716  ok :)

**Comment by PruebasTere** [comment]
ya terminé de escribir y le di push...no entiendo mucho como es esta cosa pero le di push xD

**Comment by Angelmon18** [comment]
Va, ahora abro el documento y copio lo mío

**Comment by PruebasTere** [comment]
ok, ok, me avisas

**Comment by Angelmon18** [comment]
No se guardó nada :/

**Comment by PruebasTere** [comment]
al hacer e push?

**Comment by Angelmon18** [comment]
Si, ya hice pull para obtener la actualización del documento y solo me aparece que dice "prueba"

**Comment by PruebasTere** [comment]
a mi si me sale lo mio pero al hacer el pull no me jala nada de lo tuyo :(

**Comment by Angelmon18** [comment]
Yo no he subido nada, primero quiero que me muestre lo que subiste para ahí mismo añadir lo mío

**Comment by Angelmon18** [comment]
Subiré lo mío a ver si puedes verlo

**Comment by Angelmon18** [comment]
Listo

**Comment by Angelmon18** [comment]
Dale pull

**Comment by PruebasTere** [comment]
no me jala lo que escribiste

**Comment by PruebasTere** [comment]
![1](https://user-images.githubusercontent.com/32375459/32291178-ee066786-bf01-11e7-88f4-b439ab01248b.PNG)

**Comment by PruebasTere** [comment]
es ahi verdad?

**Comment by PruebasTere** [comment]
push para enviar y pull para jalar los cambios que tú hayas echo

**Comment by Angelmon18** [comment]
Para subir es push. para actualizar es pull

**Comment by PruebasTere** [comment]
no me jala tus cambios

**Comment by Angelmon18** [comment]
Ni a mi los tuyos, no sé que está pasando jaja

**Comment by Angelmon18** [comment]
Ya subí mi parte

**Comment by PruebasTere** [comment]
no me la jala...prueba si te jala la mía

**Comment by Angelmon18** [comment]
Yo ya puedo ver tu parte

**Comment by Angelmon18** [comment]
Loq ue hice fue volver a clonar el proyecto

**Comment by PruebasTere** [comment]
ya me salió tu parte
